blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("posts", views.renderPosts, name="posts"),
    path("post_detail/<int:post_id>", views.post_detail, name="post_detail"),
]

portafolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
  path('admin/', admin.site.urls),
  path('blog', include('blog.urls', namespace='blog')),
  path('', include('portfolio.urls', namespace='portfolio')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path("", views.home, name="home"),

    #URL REGISTRO LOGIN Y CIERRE SECION
path('signup/', views.signup, name='signup'),
path('logout/', views.signout, name='logout'),
path('signin/', views.signin, name='signin'),

]

blog/models.py
from django.db import models
import datetime


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="blog/images") # para trabajar con imagenes se debe instalar esta paquete -- pip install Pillow
    date = models.DateField(default=datetime.date.today)

    def __str__(self) -> str:
        return self.title

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, DateField, URLField
from django.db.models.fields.files import ImageField
from datetime import date


class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to="portfolio/images") # para trabajar con imagenes se debe instalar esta paquete -- pip install Pillow
    url = URLField(blank=True)
    date = DateField(default=date.today)

    def __str__(self) -> str:
        return self.title

#NUEVO MODELO DEL MASTER VERA
class Curso(models.Model):
  institucion_del_curso = models.CharField(max_length=225)
  descripcion_curso = models.TextField()
  fecha_curso = models.DateField()
  numero_horas = models.PositiveIntegerField()

  def _str_(self):
    return f'{self.descripcion_curso} - {self.institucion_del_curso}'

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

@login_required(login_url=reverse_lazy('portfolio:signin'))
def renderPosts(request):
    total_posts = Post.objects.count()
    posts = Post.objects.order_by("-date")
    return render(request, "blog.html", {"posts": posts, "total_posts": total_posts})


@login_required(login_url=reverse_lazy('portfolio:signin'))
def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, "post_detail.html", {"post": post})

portfolio/views.py
from .models import Project, Curso
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy



#@login_required(login_url=reverse_lazy('portfolio:signin'))
def home (request):
    context = {
        'title': 'Yenthenny Ledesma',
        'projects': Project.objects.all(),
        'cursos': Curso.objects.all(),
    }
    return render(request, 'home.html', context)



def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {"form": UserCreationForm})
    else:

        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.create_user(
                    request.POST["username"], password=request.POST["password1"])
                user.save()
                login(request, user)
                return redirect('portfolio:home')
            except IntegrityError:
                return render(request, 'signup.html', {"form": UserCreationForm, "error": "Username already exists."})

        return render(request, 'signup.html', {"form": UserCreationForm, "error": "Passwords did not match."})


@login_required
def signout(request):
    logout(request)
    return redirect('portfolio:home')


def signin(request):
    if request.method == 'GET':
        return render(request, 'signin.html', {"form": AuthenticationForm})
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'signin.html', {"form": AuthenticationForm, "error": "Username or password is incorrect."})

        login(request, user)
        return redirect('portfolio:home')

templates/blog.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="fs-2">Posts</h1>
<h3>There are {{total_posts}} post{{total_posts|pluralize}}</h3>

{% for post in posts %}

<div class="py-3">

  <div class="card card-body bg-black">
    <div class="row">

      <div class="col-3">
        <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">

      </div>
      <div class="col-9">

        <h1>{{post.title}}</h1>
        <p>{{post.description|striptags|truncatechars:100}}</p>
        <p>{{post.date|date:'M d Y'|upper}}</p>

        <a href="{% url 'blog:post_detail' post.id %}">{{post.title}}</a>
      </div>
    </div>
  </div>
</div>

{% endfor %}

{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block content %}

{% load static %}

<!-- Hero Section -->
<header class="row bg-black">

  <div class="col-md-4">
    <img class="img-mifoto" src="{% static 'public/portafolio/imageny.jpeg' %}" />
  </div>

  <div class="col-md-8 my-auto p-4">
    <h1>I am <strong>Ryan Ray</strong></h1>
    <h3>I'm a Python FullStack Developer</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis tempora perspiciatis molestias iusto ducimus
      soluta mollitia ratione, fuga praesentium, reiciendis minima! Facere, veniam! Omnis, quod molestias quo fugit enim
      vero vitae, cumque tenetur at, impedit provident dicta laudantium quia facilis consequuntur blanditiis iste
      laborum voluptatibus libero doloribus? Pariatur voluptatem obcaecati deserunt aperiam exercitationem nam voluptas
      rerum reprehenderit minima, earum impedit saepe eos ducimus fugit itaque a nulla omnis architecto laudantium
      blanditiis? Eius ipsum quidem enim architecto fugiat porro inventore libero praesentium aperiam nulla
      exercitationem nemo soluta, culpa impedit est et doloribus ut necessitatibus odit, dicta voluptate! Vero ab nulla
      placeat.</p>
    <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'public/portafolio/Administracion General - Industrias.pdf' %}">Download my CV</a>
  </div>
</header>

<!-- Porfolio Section -->
    {% if user.is_authenticated %}
<div class="row my-4 text-center">

  <h3>My Projects</h3>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, aperiam?</p>

  {% for project in projects %}
  <div class="col-md-4 p-4">
    <div class="card bg-black card-project">
      <img src="{{project.image.url }}" class="card-img-top" />

      <div class="card-body">

        <h2>{{ project.title }}</h2>
        <p>{{ project.description }}</p>

        {% if project.url %}
        <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="__blank" rel="noreferrer">Visit the
          Project</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<div class="row my-4 text-center">
  <h3>Mis Cursos</h3>
  {% if cursos %}
      {% for curso in cursos %}
          <div class="col-md-4 p-4">
              <div class="card bg-gradient card-project">
                  <div class="card-body">
                      <h2>{{ curso.institucion_del_curso }}</h2>
                      <p><strong>Descripción:</strong> {{ curso.descripcion_curso }}</p>
                      <p><strong>Fecha:</strong> {{ curso.fecha_curso }}</p>
                      <p><strong>Horas:</strong> {{ curso.numero_horas }} horas</p>
                  </div>
              </div>
          </div>
      {% endfor %}
  {% else %}
      <p>No hay cursos disponibles.</p>
  {% endif %}
</div>
{% else %}
    {% endif %}

{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django Porfolio</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body class="text-light">

  {% include 'navbar.html' %}

  <div class="container p-4">
    {% block content %}
    {% endblock %}
  </div>

</body>

</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">RR</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
    {% if user.is_authenticated %}      
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static 'public/portafolio/Administracion General - Industrias.pdf' %}" target="_blank">Download CV</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "portfolio:logout" %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a href="{% url "portfolio:signin" %}" class="nav-link">Login</a>
        </li>
        <li class="nav-item">
          <a href="{% url "portfolio:signup" %}" class="nav-link">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">

  <h1>{{post.title}}</h1>
  <h2 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h2>

  <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">


  <div class="my-4">

  {{post.description|safe}}
  </div>
</div>

{% endblock %}

templates/signin.html
{% extends "home.html" %}

{% block content %}

<h1>Signin</h1>

<p>
{{error}}
</p>

<form action="/signin/" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button>
    Signin
  </button>
</form>

{% endblock %}

templates/signup.html
{% extends 'home.html' %} {% block content %}

<div class="container">
  <h1>Signup</h1>

  {{error}}

  <form action="/signup/" method="POST">
    {% csrf_token %} {{form.as_p}}
    <button class="btn btn-primary">Signup</button>
  </form>
</div>
{% endblock %}